version: '3.7'
services:
  nginx:
    image: nginx:latest
    deploy:
      replicas: 5
    configs:
    - source: config
      target: /etc/nginx/conf.d/default.conf
  nginxxx:
    image: nginx:latest
    deploy:
      replicas: 5
    configs:
    - source: config
      target: /etc/nginx/conf.d/default.conf
configs:
  config: 
    file: configs/nginx.conf
